name: site_www_analysis
description: Implements basic GitHub analysis of Dart's site_www repository.
publish_to: none
version: 0.0.1
homepage: https://www.github.com/parlough/site_www_analysis

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  github: ^8.0.1
  intl: ^0.17.0

dev_dependencies:
  pedantic: ^1.11.0
